In [4]:
from __future__ import print_function
import torch
'''
    pytorch
    1. 张量的概念 含义 创建 更改
    2. 求导 神经网络参数调整的过程 权重表示调整速度的快慢
    3. 损失函数
     
    
'''


In [5]:
'''
    张量操作
'''
x=torch.empty(5,3)# 5*3 matrix 未初始化
torch.zeros(5,3,dtype=torch.long)#矩阵中的元素全部是0
torch.ones(5,3,dtype=torch.long)#矩阵中的元素全部是1
torch.rand(5,3)# 生成【0,1】之间的随机数
torch.randn(5,3)# 生成均值为0，方差为1的随机数，服从标准正态分布
torch.randint(-100,100,(400,))# low high size size是一个元祖
a=torch.tensor([5.5,3])#直接从已有的值生成张量

#根据已有的形状创建张量
x = x.new_ones(6,3,dtype=torch.double) # 可以将原始矩阵的形状和值都改变

x = torch.randn_like(x,dtype=torch.float)# 随机生成与x形状相同的

x=torch.rand_like(x,dtype=torch.float)

torch.randperm(10) # 生成一个0～n-1的随机序列
#改变形状 相当于numpy中的reshape
x=torch.randn(4,4)
# y=x.view(2,8)
y=x.view(-1,8)# -1代表的是不确定的数


In [35]:
# 访问元素
x[:2]#取得前两行
x[:2,1]#取得前两行的第二列

tensor([-1.5229,  0.7999])

In [48]:
# tensor转换为numpy数组
import numpy as np 
b=torch.ones(5,3)
a = b.numpy()
a
#numpy数组转换为tensor
p=np.ones(5)
q=torch.from_numpy(a)
#numpy中的广播机制
np.add(a,1,out=a)
print(a)
print(p)
print(q)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[1. 1. 1. 1. 1.]
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [40]:
a=b=y
#torch中的广播机制
result=torch.add(a,b)
result

tensor([[ 3.0995, -3.0458, -0.6574,  0.1588, -0.4030,  1.5998, -2.2663,  0.1259],
        [-4.0349,  0.2301,  3.6296, -2.3907,  1.0407,  1.7489, -0.9352,  2.0640]])

In [51]:
# 使用cuda
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x = x.to("cuda")
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))

In [65]:
x=torch.ones(2,2,requires_grad=True)# requires_grad=True 目的是
x
y=x+2
y
print(y.grad_fn)
z=y*y*3
out = z.mean()
print(out)
print(z)
out.backward()# 反向传播应用在标量上
print(x.grad)

tensor(27., grad_fn=<MeanBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
