In [2]:
import numpy as np
# 在python中使用

In [3]:
data1=[1,2,3,4,5]
arr = np.array(data1) # list转array
data2 = [range(1,5),range(5,9)] # 二维list
arr2=np.array(data2)
tmp=arr2.tolist() # array 转 list

In [6]:
tmp = np.zeros(10)
np.zeros((3,6))
np.ones(10)
x = np.logspace(0,3,4) #(start,end,num,base=10.0) 等比数列
y = np.linspace(0,1,5)# (start,end,num) 等差数列
np.random.rand(2,3) # 创建一个2*3的数组，取之范围在（0，1）
np.random.randn(2,3) # 创建一个2*3的数组，取值范围 均值为0，方差为1

In [9]:
int_array = np.arange(5) # arange like range
float_array = int_array.astype(float) # 改变数据类型

In [13]:
float_array,int_array,int_array.dtype,arr.shape,len(arr2)

(array([0., 1., 2., 3., 4.]), array([0, 1, 2, 3, 4]), dtype('int64'), (5,), 2)

In [14]:
# 改变array的形状
tmp = arr2.reshape((4,2))

In [17]:
arr2,tmp

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [18]:
arr_flt=arr2.flatten() # 将arr2展开成一维的

In [22]:
a = np.array([0,1])
b = np.array([2,3])
ab = np.stack((a,b)).T # 数组转置

In [24]:
# 关于数组的切分

arr2[0,:] # 取第一行的所有元素
arr2[:,0] # 取第一列的所有元素
arr2[0,3] # 取第一行第四列
arr2[0,::2] # start:end:step

array([1, 2, 3, 4])

In [34]:
# 广播机制
a = np.array([[[0,0,0],
            [10,10,10],
            [20,20,20],
            [30,30,30]]])
b = np.array([0,1,2])
a+b 

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]]])

In [40]:
# 数学上的操作
nums = np.arange(5)
nums*10
nums = np.sqrt(nums)
np.ceil(nums)# 大于等于这个数的最大整数
np.floor(nums) # 向上取整
nums.mean() # 取平均值
nums.std()
# 关于numpy的判断
np.isnan()# 判断是否是nan
np.isinf(1)#判断是否是无穷
nums

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
import numpy as np

# 数组的生成和创建
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])  # [[],[]] 类似于java中二维数组的定义
c = np.array([1, 2, 3, 4], ndmin=3)  # 指定生成数组的最小维度
d = np.array([1, 2, 3, 4], dtype=complex)  # 生成数据格式为复数的数组
print(d)
a = np.arange(24)
print(a.ndim)
b = a.reshape(2, 4, 3)  # 对于三维数组，包含二维数组的数量，二维数组的形状
print(b, b.ndim)
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
x = [(1, 2, 3), (4, 5)]
a = np.asarray(x)
print(a)
# start end step
x = np.arange(10, 20, 2)
print(x)

# numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的，格式如下：
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None) endpoint 终止值是否包含
a = np.linspace(1, 10, 6)
print(a)
# numpy.logspace 函数用于创建一个于等比数列。格式如下：
# np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
b = np.logspace(1.0, 2.0, 10)  # start= base*start end=base*end
print(b)
c = np.logspace(0, 9, 10, base=2)
print(c)

# 从已有的数组中创建数组
x = [1, 2, 3]
# 从元祖列表转换
x = [(4, 5, 6), (1, 2, 3)]
a = np.asarray(x)
print(a)

# 切片和索引
a = np.arange(10)## [0,10)
s = slice(2, 7, 2)
b = a[2:7:2]
print(b)
print(a[s])
# 多维数组的切割和索引
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1:])

# 高级索引
# 整数数组索引

# 以下实例获取数组中(0,0)，(1,1)和(2,0)位置处的元素。
x = np.array([[1,  2],  [3,  4],  [5,  6]])
y = x[[0, 1, 2],  [0, 1, 0]]
print(y)

# 布尔索引

x = np.array([[0,  1,  2], [3,  4,  5], [6,  7,  8], [9, 10, 11]])
print('我们的数组是：')
print(x)
print('\n')
# 现在我们会打印出大于 5 的元素
print('大于 5 的元素是：')
print(x[x > 5])
a = np.array([np.nan,  1,2,np.nan,3,4,5])
print (a[~np.isnan(a)])

# 借助切片和...与索引数组组合
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = a[1:3, 1:3]
c = a[1:3, 1:2]
d = a[..., 1:]  # ...可以理解占位符


# 广播机制
# 形状一致，普通相乘
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = a*b
print(c)
# 形状不同，自动触发广播机制
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([1, 2, 3])
print(a+b)

# 迭代数组
a = np.arange(6).reshape(2, 3)
print(a)
print("迭代输出数组：")
for x in np.nditer(a): # iterator
    print(x, end=", ")
print("\n")

# 访问顺序
for x in np.nditer(a.T):
    print(x, end=",")
print("\n")

for x in np.nditer(a.T.copy(order="C")):# C是按行，F是按列
    print(x,end=", ")
print("\n")

for x in np.nditer(a,order='F'):
    print(x, end=", ")
print("\n")

# 修改数组元素中的值
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("原始数组 ")
print(a)

for x in np.nditer(a,op_flags=['readwrite']): # 默认是read-only
    x[...] = 2*x
print('修改后的数组是 ')
print(a)
# 使用外部循环
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("原始数组 ")
print(a)

for x in np.nditer(a,flags= ['external_loop'], order ='F'):
    print(x, end=', ')







